title: DKU UCC Events
description: Folder-based automatic event publicity workflow

theme: jekyll-theme-minimal

baseurl: "/demo-event-workflow"
url: "https://dku-ucc.github.io"

defaults:
  - scope:
      path: "events"
    values:
      layout: "event"
      type: "event"
