title: DKU UCC Event Demo
description: Folder-based automatic blog workflow
theme: jekyll-theme-minimal

# 关键：声明 events 集合
collections:
  events:
    output: true
    permalink: /events/:name/

# 设置默认布局（可选）
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "default"
